function report = report_generation(results, output_dir)
% Generate comprehensive clinical report
%
% Input: results - Structure with all analysis results
%        output_dir - Directory to save report
% Output: report - Structure with report paths

% Create output directory
if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

% Extract results
grading = results.grading;
features = results.features;
lesions = results.lesions;
quality = results.quality;

% Generate timestamp
timestamp = datestr(now, 'yyyy-mm-dd_HH-MM-SS');

% 1. Generate text report
txt_filename = fullfile(output_dir, sprintf('report_%s.txt', timestamp));
fid = fopen(txt_filename, 'w');

% Header
fprintf(fid, '========================================\n');
fprintf(fid, 'OCUPLUS AIDRSS - CLINICAL REPORT\n');
fprintf(fid, '========================================\n\n');
fprintf(fid, 'Generated: %s\n\n', datestr(now));

% Patient Information
fprintf(fid, '1. PATIENT INFORMATION\n');
fprintf(fid, '------------------------\n');
fprintf(fid, 'Patient ID: %s\n', results.patient_id);
fprintf(fid, 'Age: %d\n', results.age);
fprintf(fid, 'Gender: %s\n', results.gender);
fprintf(fid, 'Diabetes Duration: %d years\n', results.diabetes_duration);
fprintf(fid, '\n');

% Image Quality
fprintf(fid, '2. IMAGE QUALITY\n');
fprintf(fid, '------------------------\n');
fprintf(fid, 'Quality Grade: %s\n', quality.grade);
fprintf(fid, 'Quality Score: %.2f\n', quality.score);
fprintf(fid, 'Focus Score: %.2f\n', quality.focus_score);
fprintf(fid, 'Illumination Score: %.2f\n', quality.illumination_score);
fprintf(fid, '\n');

% DR Grading
fprintf(fid, '3. DR SEVERITY GRADING\n');
fprintf(fid, '------------------------\n');
fprintf(fid, 'DR Grade: %s (Level %d)\n', grading.grade_label, grading.grade);
fprintf(fid, 'Confidence: %.1f%%\n', grading.confidence * 100);
fprintf(fid, 'Referable DR: %s\n', iff(grading.is_referable, 'Yes', 'No'));
fprintf(fid, 'Vision Threatening: %s\n', iff(grading.is_vision_threatening, 'Yes', 'No'));
fprintf(fid, 'Criteria: %s\n', grading.criteria{1});
fprintf(fid, '\n');

% Lesion Detection
fprintf(fid, '4. LESION DETECTION\n');
fprintf(fid, '------------------------\n');
fprintf(fid, 'Microaneurysms: %d\n', lesions.microaneurysms.count);
fprintf(fid, 'Exudates: %d\n', lesions.exudates.count);
fprintf(fid, 'Hemorrhages: %d\n', lesions.hemorrhages.count);
fprintf(fid, 'Neovascularization: %d\n', lesions.neovascularization.count);
fprintf(fid, 'Total Lesions: %d\n', lesions.total_lesions);
fprintf(fid, '\n');

% Geometric Features
fprintf(fid, '5. GEOMETRIC FEATURES\n');
fprintf(fid, '------------------------\n');
fprintf(fid, 'Fractal Dimension: %.3f\n', features.fractal_dimension);
fprintf(fid, 'Vessel Density: %.1f%%\n', features.density);
fprintf(fid, 'Tortuosity Index: %.3f\n', features.tortuosity);
fprintf(fid, 'Branching Angle: %.1f°\n', features.branching_angle);
fprintf(fid, 'Complexity Score: %.3f\n', features.complexity_score);
fprintf(fid, '\n');

% Clinical Interpretation
fprintf(fid, '6. CLINICAL INTERPRETATION\n');
fprintf(fid, '------------------------\n');
fprintf(fid, '%s\n', features.interpretation);
fprintf(fid, '\n');

% Recommendation
fprintf(fid, '7. RECOMMENDATION\n');
fprintf(fid, '------------------------\n');
fprintf(fid, '%s\n', grading.recommendation);
fprintf(fid, '\n');

% Footer
fprintf(fid, '========================================\n');
fprintf(fid, 'Generated by OcuPlus AIDRSS v2.1.0\n');
fprintf(fid, 'This report is for clinical reference only.\n');
fprintf(fid, 'Please consult with a qualified ophthalmologist.\n');
fprintf(fid, '========================================\n');

fclose(fid);

% 2. Generate HTML report
html_filename = fullfile(output_dir, sprintf('report_%s.html', timestamp));
generate_html_report(results, html_filename);

% 3. Generate JSON data
json_filename = fullfile(output_dir, sprintf('data_%s.json', timestamp));
json_data = jsonencode(results);
fid = fopen(json_filename, 'w');
fprintf(fid, '%s', json_data);
fclose(fid);

% Return report paths
report = struct();
report.text_report = txt_filename;
report.html_report = html_filename;
report.json_data = json_filename;
report.timestamp = timestamp;

end

function generate_html_report(results, filename)
% Generate HTML report
fid = fopen(filename, 'w');

% HTML header
fprintf(fid, '<!DOCTYPE html>\n');
fprintf(fid, '<html>\n');
fprintf(fid, '<head>\n');
fprintf(fid, '    <title>OcuPlus AIDRSS Clinical Report</title>\n');
fprintf(fid, '    <style>\n');
fprintf(fid, '        body { font-family: Arial, sans-serif; margin: 40px; }\n');
fprintf(fid, '        .header { background: #2c3e50; color: white; padding: 20px; text-align: center; }\n');
fprintf(fid, '        .section { margin: 20px 0; padding: 20px; border: 1px solid #ddd; border-radius: 5px; }\n');
fprintf(fid, '        .grade-0 { color: green; }\n');
fprintf(fid, '        .grade-1 { color: yellowgreen; }\n');
fprintf(fid, '        .grade-2 { color: orange; }\n');
fprintf(fid, '        .grade-3 { color: red; }\n');
fprintf(fid, '        .grade-4 { color: darkred; }\n');
fprintf(fid, '        .metric { display: inline-block; margin: 5px; padding: 10px; background: #f8f9fa; border-radius: 5px; }\n');
fprintf(fid, '        .recommendation { background: #e8f4f8; padding: 15px; border-left: 4px solid #2196F3; }\n');
fprintf(fid, '    </style>\n');
fprintf(fid, '</head>\n');
fprintf(fid, '<body>\n');

% Header
fprintf(fid, '<div class="header">\n');
fprintf(fid, '    <h1>OcuPlus AIDRSS Clinical Report</h1>\n');
fprintf(fid, '    <p>Generated: %s</p>\n', datestr(now));
fprintf(fid, '</div>\n');

% Patient Information
fprintf(fid, '<div class="section">\n');
fprintf(fid, '    <h2>Patient Information</h2>\n');
fprintf(fid, '    <p><strong>Patient ID:</strong> %s</p>\n', results.patient_id);
fprintf(fid, '    <p><strong>Age:</strong> %d</p>\n', results.age);
fprintf(fid, '    <p><strong>Gender:</strong> %s</p>\n', results.gender);
fprintf(fid, '</div>\n');

% DR Grading
grade_class = sprintf('grade-%d', results.grading.grade);
fprintf(fid, '<div class="section">\n');
fprintf(fid, '    <h2>DR Severity Grading</h2>\n');
fprintf(fid, '    <p class="%s"><strong>Grade:</strong> %s (Level %d)</p>\n', ...
        grade_class, results.grading.grade_label, results.grading.grade);
fprintf(fid, '    <p><strong>Confidence:</strong> %.1f%%</p>\n', results.grading.confidence * 100);
fprintf(fid, '    <p><strong>Referable DR:</strong> %s</p>\n', iff(results.grading.is_referable, 'Yes', 'No'));
fprintf(fid, '    <p><strong>Criteria:</strong> %s</p>\n', results.grading.criteria{1});
fprintf(fid, '</div>\n');

% Lesions
fprintf(fid, '<div class="section">\n');
fprintf(fid, '    <h2>Lesion Detection</h2>\n');
fprintf(fid, '    <div class="metric">Microaneurysms: %d</div>\n', results.lesions.microaneurysms.count);
fprintf(fid, '    <div class="metric">Exudates: %d</div>\n', results.lesions.exudates.count);
fprintf(fid, '    <div class="metric">Hemorrhages: %d</div>\n', results.lesions.hemorrhages.count);
fprintf(fid, '    <div class="metric">Neovascularization: %d</div>\n', results.lesions.neovascularization.count);
fprintf(fid, '    <div class="metric">Total Lesions: %d</div>\n', results.lesions.total_lesions);
fprintf(fid, '</div>\n');

% Features
fprintf(fid, '<div class="section">\n');
fprintf(fid, '    <h2>Geometric Features</h2>\n');
fprintf(fid, '    <div class="metric">Fractal Dimension: %.3f</div>\n', results.features.fractal_dimension);
fprintf(fid, '    <div class="metric">Vessel Density: %.1f%%</div>\n', results.features.density);
fprintf(fid, '    <div class="metric">Tortuosity: %.3f</div>\n', results.features.tortuosity);
fprintf(fid, '    <div class="metric">Branching Angle: %.1f°</div>\n', results.features.branching_angle);
fprintf(fid, '</div>\n');

% Recommendation
fprintf(fid, '<div class="section">\n');
fprintf(fid, '    <div class="recommendation">\n');
fprintf(fid, '        <h3>Recommendation</h3>\n');
fprintf(fid, '        <p>%s</p>\n', results.grading.recommendation);
fprintf(fid, '    </div>\n');
fprintf(fid, '</div>\n');

% Footer
fprintf(fid, '<div style="margin-top: 40px; padding: 20px; background: #f8f9fa; text-align: center; color: #666;">\n');
fprintf(fid, '    <p>Generated by OcuPlus AIDRSS v2.1.0</p>\n');
fprintf(fid, '    <p>This report is for clinical reference only. Please consult with a qualified ophthalmologist.</p>\n');
fprintf(fid, '</div>\n');

fprintf(fid, '</body>\n');
fprintf(fid, '</html>\n');

fclose(fid);
end

function result = iff(condition, true_val, false_val)
% Simple conditional function
if condition
    result = true_val;
else
    result = false_val;
end
end
